"""
Core module - foundational components for the anomaly detection pipeline.

This module contains:
    - config: Centralized configuration management
    - constants: Enums, constants, and shared values
    - exceptions: Custom exception hierarchy
    - logging: Logging configuration and utilities
    - protocols: Abstract interfaces and type protocols
"""

from smartbox_anomaly.core.config import (
    FingerprintingConfig,
    InferenceConfig,
    ModelConfig,
    ObservabilityConfig,
    PipelineConfig,
    ServiceConfig,
    ServiceSLOConfig,
    SLOConfig,
    TimePeriodConfig,
    VictoriaMetricsConfig,
    get_config,
    reset_config,
    set_config,
)
from smartbox_anomaly.core.constants import (
    PERIOD_CONFIDENCE_SCORES,
    PERIOD_FALLBACK_MAP,
    TIME_PERIOD_SUFFIXES,
    AlertType,
    AnomalySeverity,
    DetectionMethod,
    IncidentAction,
    IncidentStatus,
    MetricName,
    ModelType,
    ServiceCategory,
    Thresholds,
    TimePeriod,
)
from smartbox_anomaly.core.exceptions import (
    APIError,
    CircuitBreakerOpenError,
    ConfigurationError,
    DatabaseError,
    DetectionError,
    FingerprintingError,
    IncidentNotFoundError,
    InferenceError,
    MetricsCollectionError,
    MetricsError,
    MetricsValidationError,
    ModelError,
    ModelLoadError,
    ModelNotFoundError,
    ModelTrainingError,
    ObservabilityServiceError,
    PipelineError,
    TimePeriodError,
)
from smartbox_anomaly.core.logging import (
    EventType,
    LogContext,
    configure_logging,
    get_logger,
    log_event,
    quiet_mode,
    set_log_level,
    verbose_mode,
)
from smartbox_anomaly.core.types import (
    CascadeAnalysis,
    CascadeDetectionConfig,
    DependencyContext,
    DependencyGraphConfig,
    DependencyStatus,
)
from smartbox_anomaly.core.utils import (
    build_full_service_name,
    calculate_duration_minutes,
    discover_available_models,
    ensure_directory,
    extract_base_service_names,
    format_duration,
    generate_anomaly_name,
    generate_correlation_id,
    generate_fingerprint_id,
    generate_incident_id,
    get_model_path,
    get_period_type,
    get_time_period,
    merge_dicts,
    now_iso,
    parse_service_model,
    parse_timestamp,
    safe_get_nested,
    timestamp_age_minutes,
    truncate_string,
)

__all__ = [
    # Config
    "get_config",
    "set_config",
    "reset_config",
    "PipelineConfig",
    "VictoriaMetricsConfig",
    "ModelConfig",
    "InferenceConfig",
    "FingerprintingConfig",
    "ObservabilityConfig",
    "ServiceConfig",
    "TimePeriodConfig",
    "SLOConfig",
    "ServiceSLOConfig",
    # Constants
    "AnomalySeverity",
    "IncidentStatus",
    "IncidentAction",
    "TimePeriod",
    "ServiceCategory",
    "ModelType",
    "AlertType",
    "DetectionMethod",
    "MetricName",
    "Thresholds",
    "PERIOD_FALLBACK_MAP",
    "PERIOD_CONFIDENCE_SCORES",
    "TIME_PERIOD_SUFFIXES",
    # Exceptions
    "PipelineError",
    "ModelError",
    "ModelLoadError",
    "ModelTrainingError",
    "ModelNotFoundError",
    "MetricsError",
    "MetricsCollectionError",
    "MetricsValidationError",
    "CircuitBreakerOpenError",
    "DetectionError",
    "InferenceError",
    "TimePeriodError",
    "FingerprintingError",
    "DatabaseError",
    "IncidentNotFoundError",
    "ConfigurationError",
    "APIError",
    "ObservabilityServiceError",
    # Logging
    "configure_logging",
    "get_logger",
    "set_log_level",
    "quiet_mode",
    "verbose_mode",
    "LogContext",
    "log_event",
    "EventType",
    # Utils
    "generate_fingerprint_id",
    "generate_incident_id",
    "generate_correlation_id",
    "parse_service_model",
    "build_full_service_name",
    "extract_base_service_names",
    "get_time_period",
    "get_period_type",
    "calculate_duration_minutes",
    "format_duration",
    "generate_anomaly_name",
    "ensure_directory",
    "get_model_path",
    "discover_available_models",
    "safe_get_nested",
    "merge_dicts",
    "truncate_string",
    "now_iso",
    "parse_timestamp",
    "timestamp_age_minutes",
    # Dependency types
    "DependencyStatus",
    "DependencyContext",
    "CascadeAnalysis",
    "CascadeDetectionConfig",
    "DependencyGraphConfig",
]
